# Basic Site Info
title: "Dhanvanth Voona"
logo: profile.jpg
description: >
  I know there are countless students and recent grads with Data Science projects and AI-generated summaries. 
  I aim to keep things more interesting and less predictable. To showcase my analytical approach, here’s what ChatGPT generated 
  when I asked it to summarize my learning style:
  
  "I've noticed that you're consistently curious, especially in areas like technology, machine learning, and data analysis. 
  You approach complex topics with a methodical mindset, asking detailed questions to fully understand nuances, whether it’s about LLMs,
  neural networks, applied mathematics, or Flask applications. This suggests a natural inclination towards problem-solving and critical thinking.
  
  One thing you may not realize is your adaptability in learning new subjects, especially in practical applications. 
  For example, you’ve transitioned smoothly between topics like the mathematical understanding of neurons in *C. elegans*, 
  machine learning, and data science techniques. This cross-domain agility is a valuable skill in tech-driven fields."

  This adaptability is crucial as a Data Scientist/AI Engineer, especially with new models emerging almost every week. 

  Experience Overview
  - "1+ years in Generative AI and LLMs"
  - "2+ years in Business Intelligence, data visualization, and SQL"
  - "3+ years in Deep Learning, NLP, and Computer Vision"

# Customizations
remote_theme: "pages-themes/cayman@v0.2.0"
plugins:
  - jekyll-remote-theme # Ensures the theme can be used remotely
  - jekyll-seo-tag       # Enhances SEO for your site
  - jekyll-sitemap       # Adds a sitemap for better search engine indexing
  - jekyll-feed          # Adds RSS feed support for site updates
  - jekyll-analytics     # Optional: Add Google Analytics for site traffic tracking

# Display Options
#show_downloads: true
show_search: true    # Enables search functionality for easier navigation
show_social_links: true  # Optional: Display social media links if configured

# Site Appearance
theme: jekyll-theme-cayman # Minimal theme with color contrast
color_scheme: dark         # Optional: Dark theme option for a modern look

# Optional Logo Settings
# logo: /assets/images/logo.png  # Uncomment and specify the path if you have a logo

# Social Links
social_links:
  github: "https://github.com/dhanvanth342"
  linkedin: "https://www.linkedin.com/in/dv-63192b18b/"
  #twitter: "https://twitter.com/dhanvanth342"
  # Optional: Add other social platforms if needed

# Additional Settings
permalink: /:title/ # Shortens URLs to title-only format for better readability
markdown: kramdown   # Ensures compatibility with GitHub Pages

# SEO Settings
title_separator: "-" # For readability in page titles
#google_analytics: "YOUR_TRACKING_ID" # Optional: Replace with your Google Analytics ID for tracking
