# Basic Site Info
title: "Dhanvanth Voona"
logo: /assets/profile3.jpg
description: "Curiosity and Depth in GenAI, LLMs, Machine Learning, Deep Learning and Data Analysis"


# Site Appearance
theme: jekyll-theme-minimal
